import 'sms_classes.dart';

final List<Notice> notices = [
  Notice(
      id: 1,
      read: false,
      subject: "Routine check",
      category: "Safety Notice",
      author: "Ben",
      createAt: DateTime.parse("2024-05-15"),
      aircraft: "Aircraft 2",
      deadlineAt: DateTime.parse("2024-06-10"),
      reportNumber: "R-001",
      resolved: false),
  Notice(
    id: 2,
    read: true,
    category: "Safety Notice",
    subject: "Safety Notice",
    author: "John",
    createAt: DateTime.parse("2024-05-15"),
    aircraft: "Aircraft 1",
    deadlineAt: DateTime.parse("2024-10-10"),
    reportNumber: "R-002",
  ),
  Notice(
      id: 1,
      read: false,
      subject: "Routine check",
      category: "Safety Notice",
      author: "Ben",
      createAt: DateTime.parse("2024-05-15"),
      aircraft: "Aircraft 2",
      deadlineAt: DateTime.parse("2024-06-10"),
      reportNumber: "R-001",
      resolved: false),
  Notice(
    id: 2,
    read: true,
    category: "Safety Notice",
    subject: "Safety Notice",
    author: "John",
    createAt: DateTime.parse("2024-05-15"),
    aircraft: "Aircraft 1",
    deadlineAt: DateTime.parse("2024-10-10"),
    reportNumber: "R-002",
  ),
  Notice(
      id: 1,
      read: false,
      subject: "Routine check",
      category: "Safety Notice",
      author: "Ben",
      createAt: DateTime.parse("2024-05-15"),
      aircraft: "Aircraft 2",
      deadlineAt: DateTime.parse("2024-06-10"),
      reportNumber: "R-001",
      resolved: false),
  Notice(
    id: 2,
    read: true,
    category: "Safety Notice",
    subject: "Safety Notice",
    author: "John",
    createAt: DateTime.parse("2024-05-15"),
    aircraft: "Aircraft 1",
    deadlineAt: DateTime.parse("2024-10-10"),
    reportNumber: "R-002",
  ),
  Notice(
      id: 1,
      read: false,
      subject: "Routine check",
      category: "Safety Notice",
      author: "Ben",
      createAt: DateTime.parse("2024-05-15"),
      aircraft: "Aircraft 2",
      deadlineAt: DateTime.parse("2024-06-10"),
      reportNumber: "R-001",
      resolved: false),
  Notice(
    id: 2,
    read: true,
    category: "Safety Notice",
    subject: "Safety Notice",
    author: "John",
    createAt: DateTime.parse("2024-05-15"),
    aircraft: "Aircraft 1",
    deadlineAt: DateTime.parse("2024-10-10"),
    reportNumber: "R-002",
  ),
  Notice(
      id: 1,
      read: false,
      subject: "Routine check",
      category: "Safety Notice",
      author: "Ben",
      createAt: DateTime.parse("2024-05-15"),
      aircraft: "Aircraft 2",
      deadlineAt: DateTime.parse("2024-06-10"),
      reportNumber: "R-001",
      resolved: false),
  Notice(
    id: 2,
    read: true,
    category: "Safety Notice",
    subject: "Safety Notice",
    author: "John",
    createAt: DateTime.parse("2024-05-15"),
    aircraft: "Aircraft 1",
    deadlineAt: DateTime.parse("2024-10-10"),
    reportNumber: "R-002",
  ),
  Notice(
      id: 1,
      read: false,
      subject: "Routine check",
      category: "Safety Notice",
      author: "Ben",
      createAt: DateTime.parse("2024-05-15"),
      aircraft: "Aircraft 2",
      deadlineAt: DateTime.parse("2024-06-10"),
      reportNumber: "R-001",
      resolved: false),
  Notice(
    id: 2,
    read: true,
    category: "Safety Notice",
    subject: "Safety Notice",
    author: "John",
    createAt: DateTime.parse("2024-05-15"),
    aircraft: "Aircraft 1",
    deadlineAt: DateTime.parse("2024-10-10"),
    reportNumber: "R-002",
  ),
  Notice(
      id: 1,
      read: false,
      subject: "Routine check",
      category: "Safety Notice",
      author: "Ben",
      createAt: DateTime.parse("2024-05-15"),
      aircraft: "Aircraft 2",
      deadlineAt: DateTime.parse("2024-06-10"),
      reportNumber: "R-001",
      resolved: false),
  Notice(
    id: 2,
    read: true,
    category: "Safety Notice",
    subject: "Safety Notice",
    author: "John",
    createAt: DateTime.parse("2024-05-15"),
    aircraft: "Aircraft 1",
    deadlineAt: DateTime.parse("2024-10-10"),
    reportNumber: "R-002",
  ),
  Notice(
      id: 1,
      read: false,
      subject: "Routine check",
      category: "Safety Notice",
      author: "Ben",
      createAt: DateTime.parse("2024-05-15"),
      aircraft: "Aircraft 2",
      deadlineAt: DateTime.parse("2024-06-10"),
      reportNumber: "R-001",
      resolved: false),
  Notice(
    id: 2,
    read: true,
    category: "Safety Notice",
    subject: "Safety Notice",
    author: "John",
    createAt: DateTime.parse("2024-05-15"),
    aircraft: "Aircraft 1",
    deadlineAt: DateTime.parse("2024-10-10"),
    reportNumber: "R-002",
  ),
];
